# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_password(object):
    def setupUi(self, change_password):
        change_password.setObjectName("change_password")
        change_password.resize(900, 550)
        change_password.setMinimumSize(QtCore.QSize(900, 550))
        change_password.setMaximumSize(QtCore.QSize(900, 550))
        self.centralwidget = QtWidgets.QWidget(change_password)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(72, 73, 74)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.change_password_butn = QtWidgets.QPushButton(self.frame)
        self.change_password_butn.setGeometry(QtCore.QRect(390, 330, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.change_password_butn.setFont(font)
        self.change_password_butn.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.change_password_butn.setObjectName("change_password_butn")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 130, 361, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_line.setFont(font)
        self.login_line.setMouseTracking(False)
        self.login_line.setAcceptDrops(True)
        self.login_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.login_line.setFrame(True)
        self.login_line.setObjectName("login_line")
        self.verticalLayout_2.addWidget(self.login_line)
        self.code_word_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.code_word_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.code_word_line.setFont(font)
        self.code_word_line.setMouseTracking(False)
        self.code_word_line.setAcceptDrops(True)
        self.code_word_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.code_word_line.setMaxLength(100)
        self.code_word_line.setFrame(True)
        self.code_word_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.code_word_line.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.code_word_line.setClearButtonEnabled(False)
        self.code_word_line.setObjectName("code_word_line")
        self.verticalLayout_2.addWidget(self.code_word_line)
        self.password_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_line.setFont(font)
        self.password_line.setMouseTracking(False)
        self.password_line.setAcceptDrops(True)
        self.password_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.password_line.setFrame(True)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setObjectName("password_line")
        self.verticalLayout_2.addWidget(self.password_line)
        self.repeat_password_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.repeat_password_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.repeat_password_line.setFont(font)
        self.repeat_password_line.setMouseTracking(False)
        self.repeat_password_line.setAcceptDrops(True)
        self.repeat_password_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.repeat_password_line.setFrame(True)
        self.repeat_password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeat_password_line.setObjectName("repeat_password_line")
        self.verticalLayout_2.addWidget(self.repeat_password_line)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.back = QtWidgets.QPushButton(self.frame)
        self.back.setGeometry(QtCore.QRect(10, 490, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.back.setObjectName("back")
        self.mistacke_frame = QtWidgets.QFrame(self.frame)
        self.mistacke_frame.setGeometry(QtCore.QRect(240, 0, 431, 31))
        self.mistacke_frame.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 84, 84);\n"
"}")
        self.mistacke_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mistacke_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mistacke_frame.setObjectName("mistacke_frame")
        self.name_error = QtWidgets.QLabel(self.mistacke_frame)
        self.name_error.setGeometry(QtCore.QRect(20, 0, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_error.setFont(font)
        self.name_error.setStyleSheet("")
        self.name_error.setObjectName("name_error")
        self.hide_error = QtWidgets.QPushButton(self.mistacke_frame)
        self.hide_error.setGeometry(QtCore.QRect(390, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.hide_error.setFont(font)
        self.hide_error.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"    padding: 0;\n"
"    color:  rgb(49, 49, 49);\n"
"    pandding: 3px\n"
"    \n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.hide_error.setObjectName("hide_error")
        self.label.raise_()
        self.change_password_butn.raise_()
        self.layoutWidget.raise_()
        self.back.raise_()
        self.mistacke_frame.raise_()
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(900, 25))
        self.frame_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(55, 55, 55);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 901, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.texts_layout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.texts_layout_2.setContentsMargins(3, 0, 5, 0)
        self.texts_layout_2.setSpacing(0)
        self.texts_layout_2.setObjectName("texts_layout_2")
        self.creator_2 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(12)
        self.creator_2.setFont(font)
        self.creator_2.setObjectName("creator_2")
        self.texts_layout_2.addWidget(self.creator_2)
        self.designer_2 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(12)
        self.designer_2.setFont(font)
        self.designer_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.designer_2.setObjectName("designer_2")
        self.texts_layout_2.addWidget(self.designer_2)
        self.verticalLayout.addWidget(self.frame_2)
        change_password.setCentralWidget(self.centralwidget)

        self.retranslateUi(change_password)
        QtCore.QMetaObject.connectSlotsByName(change_password)

    def retranslateUi(self, change_password):
        _translate = QtCore.QCoreApplication.translate
        change_password.setWindowTitle(_translate("change_password", "MainWindow"))
        self.change_password_butn.setText(_translate("change_password", "change password"))
        self.login_line.setPlaceholderText(_translate("change_password", "login"))
        self.code_word_line.setPlaceholderText(_translate("change_password", "code word"))
        self.password_line.setPlaceholderText(_translate("change_password", "password"))
        self.repeat_password_line.setPlaceholderText(_translate("change_password", "repeat password"))
        self.back.setText(_translate("change_password", "*back*"))
        self.name_error.setText(_translate("change_password", "error"))
        self.hide_error.setText(_translate("change_password", "X"))
        self.creator_2.setText(_translate("change_password", "<html><head/><body><p><span style=\" font-weight:600; color:#939393;\">  Create</span><span style=\" color:#939393;\"> by Patron</span></p></body></html>"))
        self.designer_2.setText(_translate("change_password", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:#939393;\">Design</span><span style=\" color:#939393;\"> by V0_1</span></p></body></html>"))
