# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_page_loading_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loading_page(object):
    def setupUi(self, loading_page):
        loading_page.setObjectName("loading_page")
        loading_page.resize(620, 370)
        self.centralwidget = QtWidgets.QWidget(loading_page)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.creator = QtWidgets.QLabel(self.frame)
        self.creator.setGeometry(QtCore.QRect(10, 320, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(12)
        self.creator.setFont(font)
        self.creator.setObjectName("creator")
        self.designer = QtWidgets.QLabel(self.frame)
        self.designer.setGeometry(QtCore.QRect(320, 320, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(12)
        self.designer.setFont(font)
        self.designer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.designer.setObjectName("designer")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 351))
        self.label.setToolTipDuration(0)
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    border: 15px solid black;\n"
"    background-color: transparent;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 431, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("image_program/logo.png"))
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.creator.raise_()
        self.designer.raise_()
        self.label_2.raise_()
        self.horizontalLayout.addWidget(self.frame)
        loading_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(loading_page)
        QtCore.QMetaObject.connectSlotsByName(loading_page)

    def retranslateUi(self, loading_page):
        _translate = QtCore.QCoreApplication.translate
        loading_page.setWindowTitle(_translate("loading_page", "MainWindow"))
        self.creator.setText(_translate("loading_page", "<html><head/><body><p><span style=\" font-weight:600; color:#939393;\">Create</span><span style=\" color:#939393;\"> by Patron</span></p></body></html>"))
        self.designer.setText(_translate("loading_page", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:#939393;\">Design</span><span style=\" color:#939393;\"> by V0_1</span></p></body></html>"))
