# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Work_page(object):
    def setupUi(self, Work_page):
        Work_page.setObjectName("Work_page")
        Work_page.resize(1200, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Work_page.sizePolicy().hasHeightForWidth())
        Work_page.setSizePolicy(sizePolicy)
        Work_page.setMinimumSize(QtCore.QSize(1200, 650))
        Work_page.setMaximumSize(QtCore.QSize(1200, 650))
        Work_page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Work_page.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Work_page)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.stackedWidget.setObjectName("stackedWidget")
        self.hello_new_user_page = QtWidgets.QWidget()
        self.hello_new_user_page.setObjectName("hello_new_user_page")
        self.welcome_lable = QtWidgets.QLabel(self.hello_new_user_page)
        self.welcome_lable.setGeometry(QtCore.QRect(260, 80, 941, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_lable.setFont(font)
        self.welcome_lable.setStyleSheet("color: rgb(131, 131, 131);")
        self.welcome_lable.setObjectName("welcome_lable")
        self.layoutWidget = QtWidgets.QWidget(self.hello_new_user_page)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 190, 1111, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.info_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.info_layout.setContentsMargins(0, 0, 0, 0)
        self.info_layout.setSpacing(2)
        self.info_layout.setObjectName("info_layout")
        self.info_first = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_first.setFont(font)
        self.info_first.setStyleSheet("color: rgb(131, 131, 131);")
        self.info_first.setObjectName("info_first")
        self.info_layout.addWidget(self.info_first)
        self.info_second = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_second.setFont(font)
        self.info_second.setStyleSheet("color: rgb(131, 131, 131);")
        self.info_second.setObjectName("info_second")
        self.info_layout.addWidget(self.info_second)
        self.info_third = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_third.setFont(font)
        self.info_third.setStyleSheet("color: rgb(131, 131, 131);")
        self.info_third.setObjectName("info_third")
        self.info_layout.addWidget(self.info_third)
        self.info_fourth = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_fourth.setFont(font)
        self.info_fourth.setStyleSheet("color: rgb(131, 131, 131);")
        self.info_fourth.setObjectName("info_fourth")
        self.info_layout.addWidget(self.info_fourth)
        self.info_fifth = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_fifth.setFont(font)
        self.info_fifth.setStyleSheet("color: rgb(131, 131, 131);")
        self.info_fifth.setObjectName("info_fifth")
        self.info_layout.addWidget(self.info_fifth)
        self.back_first_page = QtWidgets.QLabel(self.hello_new_user_page)
        self.back_first_page.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.back_first_page.setText("")
        self.back_first_page.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.back_first_page.setScaledContents(True)
        self.back_first_page.setObjectName("back_first_page")
        self.back_first_page.raise_()
        self.welcome_lable.raise_()
        self.layoutWidget.raise_()
        self.stackedWidget.addWidget(self.hello_new_user_page)
        self.info_image_page = QtWidgets.QWidget()
        self.info_image_page.setObjectName("info_image_page")
        self.image = QtWidgets.QLabel(self.info_image_page)
        self.image.setGeometry(QtCore.QRect(20, 50, 911, 491))
        self.image.setStyleSheet("QLable{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color: black;\n"
"}")
        self.image.setText("")
        self.image.setObjectName("image")
        self.like_button = QtWidgets.QPushButton(self.info_image_page)
        self.like_button.setGeometry(QtCore.QRect(870, 490, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.like_button.setFont(font)
        self.like_button.setStyleSheet("QPushButton{\n"
"    outline: none;\n"
"    background: transparent;\n"
"    border: 0;\n"
"    padding: 0;\n"
"    color: rgb(0, 0, 0);    \n"
"    pandding: 3px\n"
"}")
        self.like_button.setText("")
        self.like_button.setObjectName("like_button")
        self.tags_image = QtWidgets.QLabel(self.info_image_page)
        self.tags_image.setGeometry(QtCore.QRect(950, 50, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tags_image.setFont(font)
        self.tags_image.setStyleSheet("color: rgb(131, 131, 131);")
        self.tags_image.setObjectName("tags_image")
        self.author_image = QtWidgets.QLabel(self.info_image_page)
        self.author_image.setGeometry(QtCore.QRect(950, 130, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.author_image.setFont(font)
        self.author_image.setStyleSheet("color: rgb(131, 131, 131);")
        self.author_image.setObjectName("author_image")
        self.title_image = QtWidgets.QLabel(self.info_image_page)
        self.title_image.setGeometry(QtCore.QRect(950, 90, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_image.setFont(font)
        self.title_image.setStyleSheet("color: rgb(131, 131, 131);")
        self.title_image.setObjectName("title_image")
        self.comments = QtWidgets.QScrollArea(self.info_image_page)
        self.comments.setGeometry(QtCore.QRect(950, 160, 241, 391))
        self.comments.setWidgetResizable(True)
        self.comments.setObjectName("comments")
        self.comments_contents = QtWidgets.QWidget()
        self.comments_contents.setGeometry(QtCore.QRect(0, 0, 239, 389))
        self.comments_contents.setObjectName("comments_contents")
        self.comments_view = QtWidgets.QListWidget(self.comments_contents)
        self.comments_view.setGeometry(QtCore.QRect(0, 0, 241, 391))
        self.comments_view.setStyleSheet("QListWidget{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}")
        self.comments_view.setObjectName("comments_view")
        self.comments.setWidget(self.comments_contents)
        self.comment_line = QtWidgets.QLineEdit(self.info_image_page)
        self.comment_line.setGeometry(QtCore.QRect(950, 560, 241, 31))
        self.comment_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.comment_line.setObjectName("comment_line")
        self.add_comment_button = QtWidgets.QPushButton(self.info_image_page)
        self.add_comment_button.setGeometry(QtCore.QRect(1094, 600, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_comment_button.setFont(font)
        self.add_comment_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_comment_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.add_comment_button.setObjectName("add_comment_button")
        self.bach_info_page = QtWidgets.QLabel(self.info_image_page)
        self.bach_info_page.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.bach_info_page.setText("")
        self.bach_info_page.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.bach_info_page.setScaledContents(True)
        self.bach_info_page.setObjectName("bach_info_page")
        self.bach_info_page.raise_()
        self.image.raise_()
        self.like_button.raise_()
        self.tags_image.raise_()
        self.author_image.raise_()
        self.title_image.raise_()
        self.comments.raise_()
        self.comment_line.raise_()
        self.add_comment_button.raise_()
        self.stackedWidget.addWidget(self.info_image_page)
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.tags = QtWidgets.QComboBox(self.search_page)
        self.tags.setGeometry(QtCore.QRect(20, 120, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tags.setFont(font)
        self.tags.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tags.setStyleSheet("QComboBox{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QComboBox:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.tags.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tags.setObjectName("tags")
        self.tags.addItem("")
        self.search_label = QtWidgets.QLabel(self.search_page)
        self.search_label.setGeometry(QtCore.QRect(20, 20, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.search_label.setFont(font)
        self.search_label.setStyleSheet("color: rgb(131, 131, 131);")
        self.search_label.setObjectName("search_label")
        self.search_button = QtWidgets.QPushButton(self.search_page)
        self.search_button.setGeometry(QtCore.QRect(20, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.search_button.setObjectName("search_button")
        self.tag_lable = QtWidgets.QLabel(self.search_page)
        self.tag_lable.setGeometry(QtCore.QRect(20, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tag_lable.setFont(font)
        self.tag_lable.setStyleSheet("color: rgb(131, 131, 131);")
        self.tag_lable.setObjectName("tag_lable")
        self.author_label = QtWidgets.QLabel(self.search_page)
        self.author_label.setGeometry(QtCore.QRect(20, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.author_label.setFont(font)
        self.author_label.setStyleSheet("color: rgb(131, 131, 131);")
        self.author_label.setObjectName("author_label")
        self.authors = QtWidgets.QComboBox(self.search_page)
        self.authors.setGeometry(QtCore.QRect(20, 190, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.authors.setFont(font)
        self.authors.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.authors.setStyleSheet("QComboBox{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QComboBox:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.authors.setObjectName("authors")
        self.authors.addItem("")
        self.scrollArea = QtWidgets.QScrollArea(self.search_page)
        self.scrollArea.setGeometry(QtCore.QRect(290, 9, 901, 571))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QScrollArea:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 891, 561))
        self.scrollAreaWidgetContents_4.setStyleSheet("QWidget{\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 901, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.back_search_page = QtWidgets.QLabel(self.search_page)
        self.back_search_page.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.back_search_page.setText("")
        self.back_search_page.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.back_search_page.setScaledContents(True)
        self.back_search_page.setObjectName("back_search_page")
        self.back_search_page.raise_()
        self.tags.raise_()
        self.search_label.raise_()
        self.search_button.raise_()
        self.tag_lable.raise_()
        self.author_label.raise_()
        self.authors.raise_()
        self.scrollArea.raise_()
        self.stackedWidget.addWidget(self.search_page)
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.images_area = QtWidgets.QScrollArea(self.home_page)
        self.images_area.setGeometry(QtCore.QRect(9, 9, 1181, 571))
        self.images_area.setStyleSheet("QScrollArea{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QScrollArea:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.images_area.setWidgetResizable(True)
        self.images_area.setObjectName("images_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1171, 561))
        self.scrollAreaWidgetContents_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layout_for_img = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layout_for_img.setContentsMargins(0, 0, 0, 0)
        self.layout_for_img.setObjectName("layout_for_img")
        self.images_area.setWidget(self.scrollAreaWidgetContents_2)
        self.label_back = QtWidgets.QLabel(self.home_page)
        self.label_back.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.label_back.setText("")
        self.label_back.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.label_back.setScaledContents(True)
        self.label_back.setObjectName("label_back")
        self.label_2 = QtWidgets.QLabel(self.home_page)
        self.label_2.setGeometry(QtCore.QRect(20, 580, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(131, 131, 131);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_back.raise_()
        self.images_area.raise_()
        self.label_2.raise_()
        self.stackedWidget.addWidget(self.home_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.avatar = QtWidgets.QLabel(self.profile_page)
        self.avatar.setGeometry(QtCore.QRect(30, 30, 131, 121))
        self.avatar.setStyleSheet("QLable{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color: black;\n"
"}")
        self.avatar.setText("")
        self.avatar.setPixmap(QtGui.QPixmap("image_program/profile.png"))
        self.avatar.setObjectName("avatar")
        self.login_label = QtWidgets.QLabel(self.profile_page)
        self.login_label.setGeometry(QtCore.QRect(190, 30, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("color: rgb(131, 131, 131);\n"
"")
        self.login_label.setObjectName("login_label")
        self.upload_icon = QtWidgets.QPushButton(self.profile_page)
        self.upload_icon.setGeometry(QtCore.QRect(180, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.upload_icon.setFont(font)
        self.upload_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_icon.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.upload_icon.setObjectName("upload_icon")
        self.deleteorchangelable = QtWidgets.QLabel(self.profile_page)
        self.deleteorchangelable.setGeometry(QtCore.QRect(40, 220, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deleteorchangelable.setFont(font)
        self.deleteorchangelable.setStyleSheet("color: rgb(131, 131, 131);\n"
"")
        self.deleteorchangelable.setObjectName("deleteorchangelable")
        self.comboBox = QtWidgets.QComboBox(self.profile_page)
        self.comboBox.setGeometry(QtCore.QRect(40, 400, 271, 31))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QComboBox:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.image_on_profile_page = QtWidgets.QLabel(self.profile_page)
        self.image_on_profile_page.setGeometry(QtCore.QRect(330, 290, 350, 200))
        self.image_on_profile_page.setMinimumSize(QtCore.QSize(350, 200))
        self.image_on_profile_page.setStyleSheet("QLable{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color: black;\n"
"}")
        self.image_on_profile_page.setText("")
        self.image_on_profile_page.setObjectName("image_on_profile_page")
        self.delete_button = QtWidgets.QPushButton(self.profile_page)
        self.delete_button.setGeometry(QtCore.QRect(40, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button.setFont(font)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.delete_button.setObjectName("delete_button")
        self.change_title_button = QtWidgets.QPushButton(self.profile_page)
        self.change_title_button.setGeometry(QtCore.QRect(130, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.change_title_button.setFont(font)
        self.change_title_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_title_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.change_title_button.setObjectName("change_title_button")
        self.frame_2 = QtWidgets.QFrame(self.profile_page)
        self.frame_2.setGeometry(QtCore.QRect(740, 280, 421, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.change_title_line = QtWidgets.QLabel(self.frame_2)
        self.change_title_line.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.change_title_line.setFont(font)
        self.change_title_line.setStyleSheet("color: rgb(131, 131, 131);\n"
"")
        self.change_title_line.setObjectName("change_title_line")
        self.title_line = QtWidgets.QLineEdit(self.frame_2)
        self.title_line.setGeometry(QtCore.QRect(0, 39, 311, 31))
        self.title_line.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.title_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.title_line.setObjectName("title_line")
        self.accept_button = QtWidgets.QPushButton(self.frame_2)
        self.accept_button.setGeometry(QtCore.QRect(330, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.accept_button.setFont(font)
        self.accept_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accept_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.accept_button.setObjectName("accept_button")
        self.back_profile_page = QtWidgets.QLabel(self.profile_page)
        self.back_profile_page.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.back_profile_page.setText("")
        self.back_profile_page.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.back_profile_page.setScaledContents(True)
        self.back_profile_page.setObjectName("back_profile_page")
        self.deleteorchangelable_2 = QtWidgets.QLabel(self.profile_page)
        self.deleteorchangelable_2.setGeometry(QtCore.QRect(40, 350, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteorchangelable_2.setFont(font)
        self.deleteorchangelable_2.setStyleSheet("color: rgb(131, 131, 131);\n"
"")
        self.deleteorchangelable_2.setObjectName("deleteorchangelable_2")
        self.back_profile_page.raise_()
        self.avatar.raise_()
        self.login_label.raise_()
        self.upload_icon.raise_()
        self.deleteorchangelable.raise_()
        self.comboBox.raise_()
        self.image_on_profile_page.raise_()
        self.delete_button.raise_()
        self.change_title_button.raise_()
        self.frame_2.raise_()
        self.deleteorchangelable_2.raise_()
        self.stackedWidget.addWidget(self.profile_page)
        self.favorite_page = QtWidgets.QWidget()
        self.favorite_page.setStyleSheet("QScrollArea{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QScrollArea:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.favorite_page.setObjectName("favorite_page")
        self.my_favorite_images_label = QtWidgets.QLabel(self.favorite_page)
        self.my_favorite_images_label.setGeometry(QtCore.QRect(10, 590, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.my_favorite_images_label.setFont(font)
        self.my_favorite_images_label.setStyleSheet("color: rgb(131, 131, 131);")
        self.my_favorite_images_label.setObjectName("my_favorite_images_label")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.favorite_page)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 10, 1181, 571))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1171, 561))
        self.scrollAreaWidgetContents_3.setStyleSheet("QWidget{\n"
"    background-color: rgb(100, 100, 100)\n"
"}")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1171, 561))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.back_favorite_page = QtWidgets.QLabel(self.favorite_page)
        self.back_favorite_page.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.back_favorite_page.setText("")
        self.back_favorite_page.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.back_favorite_page.setScaledContents(True)
        self.back_favorite_page.setObjectName("back_favorite_page")
        self.back_favorite_page.raise_()
        self.my_favorite_images_label.raise_()
        self.scrollArea_3.raise_()
        self.stackedWidget.addWidget(self.favorite_page)
        self.add_new_image_page = QtWidgets.QWidget()
        self.add_new_image_page.setObjectName("add_new_image_page")
        self.add_new_image_label = QtWidgets.QLabel(self.add_new_image_page)
        self.add_new_image_label.setGeometry(QtCore.QRect(30, 40, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.add_new_image_label.setFont(font)
        self.add_new_image_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.add_new_image_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_new_image_label.setStyleSheet("color: rgb(131, 131, 131);")
        self.add_new_image_label.setObjectName("add_new_image_label")
        self.choose_path = QtWidgets.QLabel(self.add_new_image_page)
        self.choose_path.setGeometry(QtCore.QRect(30, 170, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.choose_path.setFont(font)
        self.choose_path.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.choose_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.choose_path.setStyleSheet("color: rgb(131, 131, 131);")
        self.choose_path.setObjectName("choose_path")
        self.choose_path_line = QtWidgets.QLineEdit(self.add_new_image_page)
        self.choose_path_line.setGeometry(QtCore.QRect(30, 220, 411, 21))
        self.choose_path_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 1px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.choose_path_line.setReadOnly(True)
        self.choose_path_line.setObjectName("choose_path_line")
        self.choose_path_button = QtWidgets.QPushButton(self.add_new_image_page)
        self.choose_path_button.setGeometry(QtCore.QRect(410, 220, 41, 23))
        self.choose_path_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_path_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.choose_path_button.setObjectName("choose_path_button")
        self.add_image_button = QtWidgets.QPushButton(self.add_new_image_page)
        self.add_image_button.setGeometry(QtCore.QRect(30, 440, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_image_button.setFont(font)
        self.add_image_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_image_button.setStyleSheet("QPushButton{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 3px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.add_image_button.setObjectName("add_image_button")
        self.write_tag = QtWidgets.QLabel(self.add_new_image_page)
        self.write_tag.setGeometry(QtCore.QRect(30, 250, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.write_tag.setFont(font)
        self.write_tag.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.write_tag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.write_tag.setStyleSheet("color: rgb(131, 131, 131);")
        self.write_tag.setObjectName("write_tag")
        self.write_tags_line = QtWidgets.QLineEdit(self.add_new_image_page)
        self.write_tags_line.setGeometry(QtCore.QRect(30, 300, 371, 21))
        self.write_tags_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 1px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.write_tags_line.setObjectName("write_tags_line")
        self.view_image = QtWidgets.QLabel(self.add_new_image_page)
        self.view_image.setGeometry(QtCore.QRect(770, 210, 350, 200))
        self.view_image.setMinimumSize(QtCore.QSize(350, 200))
        self.view_image.setMaximumSize(QtCore.QSize(350, 200))
        self.view_image.setStyleSheet("QLable{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color: black;\n"
"}")
        self.view_image.setText("")
        self.view_image.setScaledContents(True)
        self.view_image.setObjectName("view_image")
        self.on_view_image = QtWidgets.QLabel(self.add_new_image_page)
        self.on_view_image.setGeometry(QtCore.QRect(740, 160, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.on_view_image.setFont(font)
        self.on_view_image.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.on_view_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.on_view_image.setStyleSheet("color: rgb(131, 131, 131);")
        self.on_view_image.setObjectName("on_view_image")
        self.verdict = QtWidgets.QLabel(self.add_new_image_page)
        self.verdict.setGeometry(QtCore.QRect(30, 530, 631, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.verdict.setFont(font)
        self.verdict.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.verdict.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verdict.setStyleSheet("color: rgb(131, 131, 131);")
        self.verdict.setObjectName("verdict")
        self.write_title_line = QtWidgets.QLineEdit(self.add_new_image_page)
        self.write_title_line.setGeometry(QtCore.QRect(30, 380, 371, 21))
        self.write_title_line.setStyleSheet("QLineEdit{\n"
"    border-radius: 2 px;\n"
"    border: 2px solid rgb(40, 40, 40);\n"
"    background-color: rgb(49, 49, 49);\n"
"    padding: 1px;\n"
"    color: rgb(131, 131, 131);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.write_title_line.setObjectName("write_title_line")
        self.write_title_lable = QtWidgets.QLabel(self.add_new_image_page)
        self.write_title_lable.setGeometry(QtCore.QRect(30, 330, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.write_title_lable.setFont(font)
        self.write_title_lable.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.write_title_lable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.write_title_lable.setStyleSheet("color: rgb(131, 131, 131);")
        self.write_title_lable.setObjectName("write_title_lable")
        self.back_add_page = QtWidgets.QLabel(self.add_new_image_page)
        self.back_add_page.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.back_add_page.setText("")
        self.back_add_page.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.back_add_page.setScaledContents(True)
        self.back_add_page.setObjectName("back_add_page")
        self.back_add_page.raise_()
        self.add_new_image_label.raise_()
        self.choose_path.raise_()
        self.choose_path_line.raise_()
        self.choose_path_button.raise_()
        self.add_image_button.raise_()
        self.write_tag.raise_()
        self.write_tags_line.raise_()
        self.view_image.raise_()
        self.on_view_image.raise_()
        self.verdict.raise_()
        self.write_title_line.raise_()
        self.write_title_lable.raise_()
        self.stackedWidget.addWidget(self.add_new_image_page)
        self.welcome_back_page = QtWidgets.QWidget()
        self.welcome_back_page.setObjectName("welcome_back_page")
        self.welcome_back_label = QtWidgets.QLabel(self.welcome_back_page)
        self.welcome_back_label.setGeometry(QtCore.QRect(270, 260, 941, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_back_label.setFont(font)
        self.welcome_back_label.setStyleSheet("color: rgb(131, 131, 131);")
        self.welcome_back_label.setScaledContents(False)
        self.welcome_back_label.setObjectName("welcome_back_label")
        self.label = QtWidgets.QLabel(self.welcome_back_page)
        self.label.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image_program/back_1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.welcome_back_label.raise_()
        self.stackedWidget.addWidget(self.welcome_back_page)
        self.command_frame = QtWidgets.QFrame(self.frame)
        self.command_frame.setGeometry(QtCore.QRect(340, 590, 521, 51))
        self.command_frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(55, 55, 55);\n"
"    border-radius: 19px;\n"
"}")
        self.command_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.command_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.command_frame.setObjectName("command_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.command_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.to_home_page = QtWidgets.QPushButton(self.command_frame)
        self.to_home_page.setMinimumSize(QtCore.QSize(0, 50))
        self.to_home_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_home_page.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    border-top-left-radius: 19px;\n"
"    border-bottom-left-radius: 19px;\n"
"    padding: 0;\n"
"    pandding: 3px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: solid;    \n"
"    border-top-width: 1px;\n"
"    border-bottom-width: 1px;\n"
"    border-left-width: 1px;\n"
"    border-color: grey;\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.to_home_page.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image_program/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_home_page.setIcon(icon)
        self.to_home_page.setIconSize(QtCore.QSize(35, 35))
        self.to_home_page.setObjectName("to_home_page")
        self.horizontalLayout.addWidget(self.to_home_page)
        self.to_search_page = QtWidgets.QPushButton(self.command_frame)
        self.to_search_page.setMinimumSize(QtCore.QSize(30, 50))
        self.to_search_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_search_page.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    padding: 0;\n"
"    pandding: 3px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: solid;\n"
"    border-top-width: 1px;\n"
"    border-bottom-width: 1px;        \n"
"    border-color: grey;\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.to_search_page.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image_program/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_search_page.setIcon(icon1)
        self.to_search_page.setIconSize(QtCore.QSize(35, 35))
        self.to_search_page.setObjectName("to_search_page")
        self.horizontalLayout.addWidget(self.to_search_page)
        self.add_new_image = QtWidgets.QPushButton(self.command_frame)
        self.add_new_image.setMinimumSize(QtCore.QSize(0, 50))
        self.add_new_image.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_new_image.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    padding: 0;\n"
"    pandding: 3px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: solid;    \n"
"    border-top-width: 1px;\n"
"    border-bottom-width: 1px;\n"
"    border-color: grey;\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.add_new_image.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image_program/add_photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_new_image.setIcon(icon2)
        self.add_new_image.setIconSize(QtCore.QSize(35, 35))
        self.add_new_image.setObjectName("add_new_image")
        self.horizontalLayout.addWidget(self.add_new_image)
        self.to_favorite_page = QtWidgets.QPushButton(self.command_frame)
        self.to_favorite_page.setMinimumSize(QtCore.QSize(0, 50))
        self.to_favorite_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_favorite_page.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    padding: 0;\n"
"    pandding: 3px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: solid;    \n"
"    border-top-width: 1px;\n"
"    border-bottom-width: 1px;\n"
"    border-color: grey;\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.to_favorite_page.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image_program/favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_favorite_page.setIcon(icon3)
        self.to_favorite_page.setIconSize(QtCore.QSize(35, 35))
        self.to_favorite_page.setObjectName("to_favorite_page")
        self.horizontalLayout.addWidget(self.to_favorite_page)
        self.to_profile_page = QtWidgets.QPushButton(self.command_frame)
        self.to_profile_page.setMinimumSize(QtCore.QSize(0, 50))
        self.to_profile_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_profile_page.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    border-top-right-radius: 19px;\n"
"    border-bottom-right-radius: 19px;\n"
"    padding: 0;\n"
"    pandding: 3px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: solid;\n"
"    border-bottom-width: 1px;\n"
"    border-top-width: 1px;\n"
"    border-right-width: 1px;\n"
"    border-color: grey;\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(123, 57, 145);\n"
"}")
        self.to_profile_page.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image_program/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_profile_page.setIcon(icon4)
        self.to_profile_page.setIconSize(QtCore.QSize(35, 35))
        self.to_profile_page.setObjectName("to_profile_page")
        self.horizontalLayout.addWidget(self.to_profile_page)
        self.verticalLayout.addWidget(self.frame)
        Work_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(Work_page)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Work_page)

    def retranslateUi(self, Work_page):
        _translate = QtCore.QCoreApplication.translate
        Work_page.setWindowTitle(_translate("Work_page", "MainWindow"))
        self.welcome_lable.setText(_translate("Work_page", "welcome to CyberWallPapper for the first time!\n"
"i want to introduce you to the app\'s navigation."))
        self.info_first.setText(_translate("Work_page", "first button - is home page. there you can see a photo in cyberpunk style."))
        self.info_second.setText(_translate("Work_page", "second button - is search page. there you can find the photo you need by tag."))
        self.info_third.setText(_translate("Work_page", "third button - is add new photo page. there you can add new photo into the program."))
        self.info_fourth.setText(_translate("Work_page", "fourth button - is favourites photo page. there you can find photos that you marked as favorites."))
        self.info_fifth.setText(_translate("Work_page", "fifth button - is profile and settings page. there you can view your profile and settings."))
        self.tags_image.setText(_translate("Work_page", "tag:"))
        self.author_image.setText(_translate("Work_page", "author:"))
        self.title_image.setText(_translate("Work_page", "title:"))
        self.add_comment_button.setText(_translate("Work_page", "add comment"))
        self.tags.setItemText(0, _translate("Work_page", "all"))
        self.search_label.setText(_translate("Work_page", "search"))
        self.search_button.setText(_translate("Work_page", "search!"))
        self.tag_lable.setText(_translate("Work_page", "tag"))
        self.author_label.setText(_translate("Work_page", "author"))
        self.authors.setItemText(0, _translate("Work_page", "all"))
        self.label_2.setText(_translate("Work_page", "home page"))
        self.login_label.setText(_translate("Work_page", "login"))
        self.upload_icon.setText(_translate("Work_page", "upload new icon"))
        self.deleteorchangelable.setText(_translate("Work_page", "delete/change title image"))
        self.delete_button.setText(_translate("Work_page", "delete"))
        self.change_title_button.setText(_translate("Work_page", "change title"))
        self.change_title_line.setText(_translate("Work_page", "change title"))
        self.accept_button.setText(_translate("Work_page", "accept"))
        self.deleteorchangelable_2.setText(_translate("Work_page", "choose image"))
        self.my_favorite_images_label.setText(_translate("Work_page", "my favorite images"))
        self.add_new_image_label.setText(_translate("Work_page", "add new image."))
        self.choose_path.setText(_translate("Work_page", "choose the path to the image."))
        self.choose_path_button.setText(_translate("Work_page", "..."))
        self.add_image_button.setText(_translate("Work_page", "add image."))
        self.write_tag.setText(_translate("Work_page", "write one tag to the photo. (this is necessary in order to find your photo)"))
        self.on_view_image.setText(_translate("Work_page", "this is how your photo will look in the gallery:"))
        self.verdict.setText(_translate("Work_page", "verdict:  (waiting for the photo to be uploaded)"))
        self.write_title_lable.setText(_translate("Work_page", "write title for photo"))
        self.welcome_back_label.setText(_translate("Work_page", "welcome back!\n"
"we\'ve been waiting for you for a long time."))

